### ISSUE TITLE
Version of node and packages

### ISSUE THREAD

**Issue by sboily** [mattermost/mattermost-interactive-post-demo#1]
Hello,

Can you give us your node, serverless and plugins versions, maybe your package.json?

For information, with nodejs 4, it doesn't works. I have this error.

`Serverless plugin "serverless-python-requirements" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.`

With nodejs 8.0 this issue is fixed. But i have another one.

```
Serverless: Excluding development dependencies...
_stream_readable.js:545
  switch (state.pipesCount) {
               ^

TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)
```

Thank you.

**Comment by sboily** [comment]
For information, it works with node 7.0.

**Comment by megaerki** [comment]
I'm getting the same error with node 7.0 and 8.1

X@Y:~/mattermost-interactive-post-demo-master$ sudo serverless deploy -v
Serverless: Installing required Python packages for runtime python2.7...
Serverless: Linking required Python packages...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
_stream_readable.js:545
  switch (state.pipesCount) {
               ^

TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)

**Comment by hanzei** [comment]
Hey @sboily,

Sorry for loosing track of this issue. Do still encounter this issue with node version 10 or 11?

**Comment by sboily** [comment]
Hello @hanzei, i don't know, i haven't tested with another version than 4, 7 and 8.

**Comment by hanzei** [comment]
Tested and works with `v11.11.0`.

@sboily Would you be open to test with a newer version of node?

**Comment by hanzei** [comment]
Closing as this is fixed with a newer node version.
